src/Entity/Job.php
<?php

namespace App\Entity;

use App\Repository\JobRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JobRepository::class)]
class Job
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $country = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $remote_allowed = null;

    #[ORM\Column]
    private ?float $salary_range = null;

    #[ORM\Column]
    private ?float $salary_max = null;

    #[ORM\ManyToOne(inversedBy: 'jobs')]
    private ?Category $category = null;

    #[ORM\ManyToMany(targetEntity: JobType::class, inversedBy: 'jobs')]
    private Collection $job_types;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'jobs')]
    private Collection $applicants;

    #[ORM\ManyToOne(inversedBy: 'jobs')]
    private ?Company $company = null;

    public function __construct()
    {
        $this->job_types = new ArrayCollection();
        $this->applicants = new ArrayCollection();
    }
    public function __toString()
    {
        return $this->getTitle();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function isRemoteAllowed(): ?bool
    {
        return $this->remote_allowed;
    }

    public function setRemoteAllowed(bool $remote_allowed): static
    {
        $this->remote_allowed = $remote_allowed;

        return $this;
    }

    public function getSalaryRange(): ?float
    {
        return $this->salary_range;
    }

    public function setSalaryRange(float $salary_range): static
    {
        $this->salary_range = $salary_range;

        return $this;
    }

    public function getSalaryMax(): ?float
    {
        return $this->salary_max;
    }

    public function setSalaryMax(float $salary_max): static
    {
        $this->salary_max = $salary_max;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, JobType>
     */
    public function getJobTypes(): Collection
    {
        return $this->job_types;
    }

    public function addJobType(JobType $jobType): static
    {
        if (!$this->job_types->contains($jobType)) {
            $this->job_types->add($jobType);
        }

        return $this;
    }

    public function removeJobType(JobType $jobType): static
    {
        $this->job_types->removeElement($jobType);

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getApplicants(): Collection
    {
        return $this->applicants;
    }

    public function addApplicant(User $applicant): static
    {
        if (!$this->applicants->contains($applicant)) {
            $this->applicants->add($applicant);
        }

        return $this;
    }

    public function removeApplicant(User $applicant): static
    {
        $this->applicants->removeElement($applicant);

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }
}

src/Entity/JobType.php
<?php

namespace App\Entity;

use App\Repository\JobTypeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JobTypeRepository::class)]
class JobType
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToMany(targetEntity: Job::class, mappedBy: 'job_types')]
    private Collection $jobs;

    public function __construct()
    {
        $this->jobs = new ArrayCollection();
    }
    public function __toString()
    {
        return $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Job>
     */
    public function getJobs(): Collection
    {
        return $this->jobs;
    }

    public function addJob(Job $job): static
    {
        if (!$this->jobs->contains($job)) {
            $this->jobs->add($job);
            $job->addJobType($this);
        }

        return $this;
    }

    public function removeJob(Job $job): static
    {
        if ($this->jobs->removeElement($job)) {
            $job->removeJobType($this);
        }

        return $this;
    }
}

src/Controller/JobController.php
<?php

namespace App\Controller;

use App\Entity\Job;
use App\Entity\Company;
use App\Repository\CategoryRepository;
use App\Repository\CompanyRepository;
use App\Repository\JobRepository;
use App\Repository\JobTypeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class JobController extends AbstractController
{
    #[Route('/jobs', name: 'app_jobs')]
    public function index(JobRepository $jobRepository, CategoryRepository $categoryRepository,CompanyRepository $companyRepository, Request $request): Response
    
    {
        $category = $request->query->get('category');
        $company = $request->query->get('company');
       

        if ($category) {
            $jobs = $jobRepository->findByCategory($category);
        } elseif($company) {
            $jobs = $jobRepository->findByCompany($company);
        }
          
          
         else {
            $jobs = $jobRepository->findAll();
        }
        
        


        $categories = $categoryRepository->findAll();
        $companies = $companyRepository->findAll();
       

        return $this->render('job/index.html.twig', [
            'jobs' => $jobs,
            'categories' => $categories,
            'companies' => $companies,
            'current_category' => $category,
            'current_company' => $company,
           
        ]);
    }


    #[Route('/jobs/{id}', name: 'app_job_show')]
    public function show(
        Job $job,
        Request $request,
        EntityManagerInterface $entityManager,
        Security $security,
        SessionInterface $session
    ): Response {
        return $this->render('job/show.html.twig', [
            'job' => $job,
        ]);
    }
}

templates/job/index.html.twig
{% extends 'base.html.twig' %} {% block title %}Hello jobController!{% endblock
%} {% block body %}
<div class="container-fluid"></div>
<div class="row">
  <div
    class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary px-4"
    id="sidebar"
  >
    <h2 class="pb-2 border-bottom">Filter</h2>
    <div class="row g-1 py-1 row-cols-1">
      <h3 class="row">Categories</h3>
      <div class="row">
          <ul class="list-group">
              <li class="list-group-item {% if current_category == "" %}active{% endif %}">
                  <a href="{{ path('app_jobs') }}">All</a>
                </li>
                {% for category in categories %}
                <li class="list-group-item {% if category.id == current_category %}active{% endif %}">
                    <a href="{{ path('app_jobs', { category: category.id }) }}">{{
                        category.name
                    }}</a>
                </li>
                
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="row g-4 py-5 row-cols-1 ">
      <h3>Companies</h3>
      <ul class="list-group">
        <li class="list-group-item {% if current_company == "" %}active{% endif %}">
          <a href="{{ path('app_jobs') }}">All</a>
        </li>
        {% for company in companies %}
        <li class="list-group-item {% if company.id == current_company %}active{% endif %}">
             <a href="{{ path('app_jobs', { company: company.id }) }}">{{
            company.name
          }}</a>
        </li>

        {% endfor %}
      </ul>
    </div>
  </div>

  <div class="col-md-9 ms-sm-auto col-lg-10 px-md-4" id="featured-3">
    <h2 class="pb-2 border-bottom">All Jobs</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
      {% for job in jobs %}

      <div class="feature col">
        <div
          class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3"
        >
          <svg class="bi" width="1em" height="1em">
            <use xlink:href="#collection"></use>
          </svg>
        </div>
        <h3 class="fs-2 text-body-emphasis">{{ job.title }}</h3>
        <p>{{ job.description | raw }}</p>
        <a href="{{ path('app_job_show', { id: job.id }) }}" class="icon-link">
          More details
          <svg class="bi"><use xlink:href="#chevron-right"></use></svg>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/job/job.html .twig
{% extends 'base.html.twig' %}

{% block title %}Hello JobController!{% endblock %}

{% block body %}
<div class="container px-4 py-5" id="hanging-icons">
    <h2 class="pb-2 border-bottom">Hanging icons</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
      <div class="col d-flex align-items-start">
        <div class="icon-square text-body-emphasis bg-body-secondary d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">
          <svg class="bi" width="1em" height="1em"><use xlink:href="#toggles2"></use></svg>
        </div>
        <div>
          <h3 class="fs-2 text-body-emphasis">Featured title</h3>
          <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
          <a href="#" class="btn btn-primary">
            Primary button
          </a>
        </div>
      </div>
      <div class="col d-flex align-items-start">
        <div class="icon-square text-body-emphasis bg-body-secondary d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">
          <svg class="bi" width="1em" height="1em"><use xlink:href="#cpu-fill"></use></svg>
        </div>
        <div>
          <h3 class="fs-2 text-body-emphasis">Featured title</h3>
          <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
          <a href="#" class="btn btn-primary">
            Primary button
          </a>
        </div>
      </div>
      <div class="col d-flex align-items-start">
        <div class="icon-square text-body-emphasis bg-body-secondary d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">
          <svg class="bi" width="1em" height="1em"><use xlink:href="#tools"></use></svg>
        </div>
        <div>
          <h3 class="fs-2 text-body-emphasis">Featured title</h3>
          <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
          <a href="#" class="btn btn-primary">
            Primary button
          </a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/job/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	JOB category
{% endblock %}

{% block body %}


	<div class="px-4 py-5 my-5 text-center">
		<h1 class="display-5 fw-bold text-body-emphasis">{{ job.title }}</h1>
		<div class="col-lg-6 mx-auto">
			<p class="lead mb-4">{{ job.description|raw }}</p>
			<div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
				<button type="button" class="btn btn-primary btn-lg px-4 gap-3">Apply</button>
			</div>
		</div>
	</div>

	<div class="container py-3">
		<header>
			<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
				<a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
					<svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewbox="0 0 118 94" role="img">
						<title>Bootstrap</title>
						<path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path>
					</svg>
					<span class="fs-4">JOB INFORMATION</span>
				</a>


			</div>

			<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
				<h1 class="display-4 fw-normal text-body-emphasis">COMPANIES</h1>
				<p class="fs-5 text-body-secondary">
					IT professionals work across various industries and sectors, utilizing technology to solve problems, improve efficiency, and innovate. Here are some key aspects of IT job roles.</p>
			</div>
		</header>

		<main>
			<div class="row row-cols-1 row-cols-md-4 mb-4 text-center">
				<div class="col">
					<div class="card mb-4 rounded-3 shadow-sm">
						<div class="card-header py-3">
							<h4 class="my-0 fw-normal">NAME</h4>
						</div>
						<div class="card-body">


							<ul class="list-unstyled mt-3 mb-4">
								<li>{{ job.company }}</li>

							</ul>
							
						</div>
					</div>
				</div>
				<div class="col">
					<div class="card mb-4 rounded-3 shadow-sm">
						<div class="card-header py-3">
							<h4 class="my-0 fw-normal">COUNTRY</h4>
						</div>
						<div class="card-body">

							<ul class="list-unstyled mt-3 mb-4">
								<li>{{ job.country }}</li>

							</ul>
							


						</ul>

					</div>
				</div>
			</div>

			<div class="col">
				<div class="card mb-4 rounded-3 shadow-sm">
					<div class="card-header py-3">
						<h4 class="my-0 fw-normal">salary</h4>
					</div>
					<div class="card-body">

						<ul class="list-unstyled mt-3 mb-4">
							<li>from {{ job.salaryRange }} to {{ job.salarymax }}</li>

						</ul>
						


					</div>


				</div>
			</div>

			<div class="col">
				<div class="card mb-4 rounded-3 shadow-sm">
					<div class="card-header py-3">
						<h4 class="my-0 fw-normal">city</h4>
					</div>
					<div class="card-body">


						<ul class="list-unstyled mt-3 mb-4">
							<li>{{ job.city }}</li>

						</ul>
						
					</ul>
				</div>
			</div>
		</div>


	</div>


{% endblock %}